### ISSUE TITLE
Issue with listing mutation using DepMap data 23Q4

### ISSUE THREAD

**Issue by RachelSmid** [ytakemon/GRETTA#37]
Used 
list_mutations(gene = "KRAS", is_hotspot =TRUE, data_dir = gretta_data_dir)
and got the error 
Error in `.data$Annotation_Transcript`:
! Column `Annotation_Transcript` not found in `.data`.
Run `rlang::last_trace()` to see where the error occurred.

Same issue when is_hotspot =FASLE

**Comment by anspinou** [comment]
I have the same issue -also with select_cell_lines(). It seems that the mut_calls.rda of the 23Q4 version is missing the CGA_WES_AC and Annotation_Transcript columns.

**Comment by ytakemon** [comment]
Hi @RachelSmid and @anspinou, 

Thanks for reporting this. It looks like this issue was due to changes in the format that DepMap reports their mutations. I've added a fix so `list_mutations(gene = "KRAS", is_hotspot =TRUE, data_dir = gretta_data_dir)` now works without issue using the 23Q4 dataset. Please update your GRETTA to the latest version, 2.5.0, and try again. 

Please let me know how it goes.

**Comment by ytakemon** [comment]
Hi @anspinou  - The container is being rebuilt, but it is going to take a while as it is quite large. For the time being feel free to use the recipe I've uploaded here: https://github.com/ytakemon/GRETTA/blob/main/Singularity/Singularity.GRETTA.def
